import React from 'react'
import { AppProps } from 'next/app'
import '../styles/index.css'
import Layout from '../components/Layout'
import Head from 'next/head'
import 'react-multi-carousel/lib/styles.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Booking | Bitsofts </title>
                <link rel="icon" href="/favicon/icon/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon/favicon.ico" />
                <link href="css/fonts.googleapis.com/css7c3b.css?family=Playfair+Display:400,700|Work+Sans:300,400,700" rel="stylesheet" />
                <link href="css/css7c3b.css" rel="stylesheet" />
                <link href="css/A.fonts,,_flaticon,,_font,,_flaticon.css+css,,_aos.css+css,,_style.css,Mcc.vCq_W-I72t.css.pagespeed.cf.Y1uFS9zq8K.css" rel="stylesheet" />
                <link href="css/mediaelementplayer.min.css" rel="stylesheet" />
              

                <link rel="stylesheet" href="css/fonts,_icomoon,_style.css+css,_bootstrap.min.css+css,_magnific-popup.css+css,_jquery-ui.css+css,_owl.carousel.min.css+css,_owl.theme.default.min.css+css,_bootstrap-datepicker.css" />
                <script type="text/javascript" src='js/bootstrap.min.js' />
                <script type="text/javascript" src='js/bootstrap-datepicker.min.js+aos.js.pagespeed.jc.kGiDTTVIyU.js' />
                <script type="text/javascript" src='js/jquery-3.3.1.min.js' />
                <script type="text/javascript" src='js/jquery-migrate-3.0.1.min.js+jquery-ui.js+popper.min.js.pagespeed.jc.qzvxj00HwO.js' />
                <script type="text/javascript" src='js/main.js' />
                <script type="text/javascript" src='js/mediaelement-and-player.min.js' />
                <script type="text/javascript" src='js/owl.carousel.min.js+jquery.stellar.min.js+jquery.countdown.min.js+jquery.magnific-popup.min.js.pagespeed.jc.Bofm_WgbFP.js' />
              

                
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>

          

       
        </>

    )

}

export default MyApp